### PR TITLE
Add support for different word lists

### PR DESCRIPTION
**Pull request by vespian**
This PR adds support for some extra wordlists:
* EFF small words
* original Diceword lists
along with the support for custom/user provided lists. The API has not changed, only new functions were added:
* `GenerateFromWordlist`
* `WordAtWordlist`
See the godocs for details.

### CODE REVIEW

**Comment by sethvargo** [comment]
Hi @vespian 

Thank you for the Pull Request. I'd like to understand a little more about the motivation for these changes. There seem to be quite a few new APIs, and I prefer to keep the interface for client libraries like this as small as possible. 

If we want to allow users to customize their list, I think it makes more sense to have a default package-level API that does the default things, and then instead create an instance of a generator which accepts more customization like [here](https://github.com/sethvargo/go-password/pull/5).

**Comment by vespian** [comment]
Hi @sethvargo 

> Thank you for the Pull Request. I'd like to understand a little more about the motivation for these changes. 

Up until now, the library does not offer a way to use custom lists, like "small" list from EFF [1]. What is more, some people may want to use e.g. localized list, e.g. NL, PL, RU, etc...

> There seem to be quite a few new APIs, and I prefer to keep the interface for client libraries like this as small as possible.

I agree about keeping the interface of the libraries short and sweet. Unfortunately, the current API does not offer a way to specify the list that should be used for generation. On the other hand, we probably do not want to break backwards compatibility. Hence the new methods. The approach you used in the PR you linked to is very similar to the one in this PR - the old interface calls new one underneath and both coexist in the new version of the library.

An alternative could be following the vgo approach and releasing `v1` version of the library, using a different import path. This is doable :)

> instance of a generator which accepts more customization like here.
* creating generator/new object on each call to the library, and then discarding it seems inefficient
* do we need state in such a simple library? We have here only one param here - wordlist to use. In the case of the password generator, this makes much more sense as there are 4 different call arguments, and we may want to cache them, in order to keep func. calls short and sweet.
* `GenerateFromWordlist(numWords, WordlistEFFBig)` I believe is more explicit and readable than creating a generator and then calling the generator. 

Cheers
pr

[1] https://www.eff.org/files/2016/09/08/eff_short_wordlist_2_0.txt

**Comment by sethvargo** [comment]
> Up until now, the library does not offer a way to use custom lists, like "small" list from EFF [1]. What is more, some people may want to use e.g. localized list, e.g. NL, PL, RU, etc...

Oops my fault

> creating generator/new object on each call to the library, and then discarding it seems inefficient

Eh - that's how most of Go core works actually

> do we need state in such a simple library? We have here only one param here - wordlist to use.

For now - my experience shows that, over time, the customization users want expands, and then you have more methods, and more methods, etc. As opposed to a configuration struct which makes things easy to add without breaking the API.

> `GenerateFromWordlist(numWords, WordlistEFFBig)` I believe is more explicit and readable than creating a generator and then calling the generator.

I disagree 😄 . I think `diceware.NewGenerator(&diceware.GeneratorInput{WordList: diceware.WordListEFFBig}).Generate()` is. It also gives the API more flexibility in the future, and enables sharing a single instance of the generator across methods (something not possible in the current implementation).

**Comment by vespian** [comment]
> For now - my experience shows that, over time, the customization users want expands, and then you have more methods, and more methods, etc. As opposed to a configuration struct which makes things easy to add without breaking the API.

Valid point.

> I think diceware.NewGenerator(&diceware.GeneratorInput{WordList:  Diceware.WordListEFFBig}).Generate() 

A matter of taste :stuck_out_tongue: 

>  It also gives the API more flexibility in the future, and enables sharing a single instance of the generator across methods (something not possible in the current implementation).

Another valid point.

OK, let's do it the way you suggest :) I will try to find some time to do the rewrite.

**Comment by sethvargo** [comment]
@vespian if you're okay with it, I'll take your code and then update it. I can do it today/tomorrow. I feel bad having you do extra work.

**Comment by vespian** [comment]
> @vespian if you're okay with it, I'll take your code and then update it. I can do it today/tomorrow. I feel bad having you do extra work.

Both are fine/up2you :) You already made some effort creating this nice library, the least I can do is to contribute.

**Pull request closed without merging**
